[[provider_endpoints]]
name = "osmosis"
# After test needs to change prod
rest = "https://api.osmo-api.staging.ojo.network"
websocket = "api.osmo-api.staging.ojo.network"

[[provider_endpoints]]
name = "crescent"
rest = "https://api.cresc-api.staging.ojo.network"
websocket = "api.cresc-api.staging.ojo.network"

[[provider_endpoints]]
name = "binance"
rest = "https://api1.binance.com"
websocket = "stream.binance.com:9443"

[[provider_endpoints]]
name = "eth-uniswap"
rest = "https://api.studio.thegraph.com/query/46403/unidexer/version/latest"
websocket = "not supported"
